# name = input("Enter your name:")
# color = input("Enter your favourite color name:")
# Bird = input("Enter a favourite bird name:")
# animal = input("Enter a animal name:")
# teacher = input("Enter a Teacher Name: ")
# collage = input("Enter your collage name:")
# friend = input("Enter your friends name: ")
# rank = int(input("Enter Your rank:"))
# marks =  float(input("Enter your pesentage:"))
# c=complex(input("ENter a complex number:"))
l=list(input("Enter  a list:"))
t=tuple(input("Enter a tuple:")) 
s = set(input("enter a set: "))
# d = dict(input("enter a dictonary:" ))
# bo=bool(input("enter a boolean type"))


# print("my Rank is",rank)
# print("my percentage is:",marks)
# print("complex number is:")
print("list is:"+l,type(l))
print("my tuple is:"+t ,type(t))
print("set is:"+s,type(s))
# print("dictonary is:"+d,type(d))
# print("boolean is:"+bo,type(bo))
# # print("My name is: " +name,end="")
# print(friend+ "are my some chutiya friens",end="")
# print("i love " + animal,end="")
# print("but my friends" +friend)
# print("also look like"+Bird,end="")